import type { Metadata } from "next";
import { Geist, Geist_Mono ,Inter} from "next/font/google";
import "./globals.css";
import  HoverFooter from "./components/footer_setup";
import { NavBar } from "./components/tubelight-navbar"
import Grainient from '@/app/components/Grainient';


 const navItems = [
    { name: 'Home', url: '/', icon: 'Home' },
        { name: 'Mods', url: '/mods', icon: 'FolderGit' },
            { name: 'Send', url: '/send', icon: 'Send' },
    { name: 'About', url: '/about', icon: 'Info' },

    { name: 'Contact', url: '/contact', icon: 'Mail' }
  ];
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mods Haven - Game Modification Platform",
  description: "Generated by create next app",
  icons: {
    icon: '/icon/logo_1.ico', 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <NavBar items={navItems} />
  <div style={{ width: '100%', height: '100%', position: 'fixed', top: 0, left: 0 }}>
        <Grainient
          color1="#202020"
          color2="#717171"
          color3="#202020"
          timeSpeed={0.4}
          colorBalance={0}
          warpStrength={0.3}
          warpFrequency={5}
          warpSpeed={2}
          warpAmplitude={50}
          blendAngle={0}
          blendSoftness={0.05}
          rotationAmount={500}
          noiseScale={2}
          grainAmount={0.1}
          grainScale={2}
          grainAnimated={false}
          contrast={1.5}
          gamma={1}
          saturation={1}
          centerX={0}
          centerY={0}
          zoom={1.5}
        />
      </div>


       
        {children}
        <HoverFooter />
      </body>
    </html>
  );
}
