import type { Metadata } from "next";
import { Geist, Geist_Mono ,Inter} from "next/font/google";
import "./globals.css";
import  HoverFooter from "./components/footer_setup";
import { NavBar } from "./components/tubelight-navbar"


 const navItems = [
    { name: 'Home', url: '/', icon: 'Home' },
        { name: 'Mods', url: '/mods', icon: 'FolderGit' },
            { name: 'Send', url: '/send', icon: 'Send' },
    { name: 'About', url: '/about', icon: 'Info' },

    { name: 'Contact', url: '/contact', icon: 'Mail' }
  ];
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mods Haven - Game Modification Platform",
  description: "Generated by create next app",
  icons: {
    icon: '/icon/logo_1.ico', 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <NavBar items={navItems} />
  

       
        {children}
        <HoverFooter />
      </body>
    </html>
  );
}
