import Image from "next/image";
import SplitText from "@/app/components/SplitText";
import DecryptedText from '@/app/components/DecryptedText';
import Grainient from '@/app/components/Grainient';
import { CarFront, ArrowUpRight, Map, Truck, CalendarFold, FolderArchive,Copyright,Download,BadgeCheck } from 'lucide-react';
import { div } from "motion/react-client";
import type { Metadata } from "next";


const mods =
{
  "_id": {
    "$oid": "68c15edd0c10e9cc2ae3f85b"
  },
  "name": "Lexus LFA",
  "description": "Experience the V10 symphony with the Lexus LFA mod for BeamNG.drive! Drive this legendary supercar with stunning detail and realistic handling. #BeamNG #LexusLFA #Supercar #CarMod #V10",
  "author": "Phaien",
  "game": "BeamNG.drive",
  "downloads_size": "183 MB",
  "AD_link": "https://sawutser.top/4/9283523",
  "download_link": "https://download.modshaven.com/Lexus_LFA_revamped.zip",
  "mod_image": "https://image.modshaven.com/mods/1765456304016-1757503197833-2012_lexus_lfa_nurburgring_package_by_bhw2279_dfe5mef-fullview.webp",
  "date_added": {
    "$date": "2025-09-10T00:00:00.000Z"
  },
  "createdAt": {
    "$date": "2025-09-10T11:19:57.851Z"
  },
  "updatedAt": {
    "$date": "2026-02-24T00:51:00.283Z"
  },
  "__v": 3,
  "downloads": 3076,
  "images": [
    "https://image.modshaven.com/mods/1765456304837-1757503197833-2012_lexus_lfa_nurburgring_package_by_bhw2279_dfe5mef-fullview.webp"
  ],
  "ads_mode": 1,
  "brand": "Lexus",
  "mod_type": "car",
  "featured": false,
  "slug": "lexus-lfa",
  "tags": [],
  "Virustotal_link": "https://www.virustotal.com/gui/file/fb821ed4be0b2f46557d63c7775929c2027ee3c2e1f0bf0f2caa5da041ce3ff7"
}

export const metadata: Metadata = {
  title: `${mods.name} - Mods Haven`,
  description: "Generated by create next app",
  icons: {
    icon: '/icon/logo_1.ico',
  },
};
export default function Home() {
  return (
    <>
      <div style={{ position: 'fixed', inset: 0, zIndex: 0, width: '100%', height: '100%' }}>
        <Grainient
          color1="#202020"
          color2="#717171"
          color3="#202020"
          timeSpeed={0.4}
          colorBalance={0}
          warpStrength={0.3}
          warpFrequency={5}
          warpSpeed={2}
          warpAmplitude={50}
          blendAngle={0}
          blendSoftness={0.05}
          rotationAmount={500}
          noiseScale={2}
          grainAmount={0.1}
          grainScale={2}
          grainAnimated={false}
          contrast={1.5}
          gamma={1}
          saturation={1}
          centerX={0}
          centerY={0}
          zoom={1.5}
        />
      </div>
      <div className="relative z-10 justify-center  m-8 flex flex-row gap-8" style={{ minHeight: '100vh', padding: '48px 0' }}>

        {/* Main Content Placeholder */}
        <main className="flex-1 p-8 justify-center items-center">
            {/* mod details section */}
          <div className="flex gap-4 items-center mx-auto p-10 justify-center flex-col  sm:flex-row">
             {/* mod image */}
            <div className="bg-black/30 backdrop-blur-lg w-full h-120 rounded-[1rem]">

            </div>
            {/* mod details */}
            <div className="bg-black/30 backdrop-blur-lg w-full h-120 rounded-[1rem] flex flex-col gap-4 p-4">
              <h2 className="text-[2.4rem] font-[800]">{mods.name}</h2>
              <hr />
              <p className="text-[1rem ] font-[900]">{mods.description}</p>
             <hr />
              <div className="flex flex-col gap-2 px-2">
                <div className="flex gap-2">
                  <div className="border-2 border-[#5e5e60] w-[100px] p-1 rounded-[0.5rem] bg-[#363638] flex items-center justify-center gap-2">
                   <Copyright className="w-4 h-4" />
                    <p className="text-[1rem] font-[700]"> {mods.author}</p>
                  </div>
                    <div className="border-2 border-[#563a1a] w-[160px] p-1 rounded-[0.5rem] bg-[#362a1f] flex items-center justify-center gap-2">
                  <img src={mods.game === "BeamNG.drive" ? "/icon/icon-beamng.ico" : "/icon/icon-assetto.ico"} alt={mods.game} width={24} height={24} style={{ borderRadius: 4 }} /> 
                     <p className="text-[1rem] font-[700]"> {mods.game}</p>
                  </div>
                </div>
                <div>
  <div className="border-2 border-[#265619] w-[210px] p-1 rounded-[0.5rem] bg-[#22351e] flex items-center justify-center gap-2">
                    <BadgeCheck className="w-5 h-5 text-green-500" />
                    <p className="text-[1rem] font-[700] ">See VirusTotal <a className="text-green-500 underline" href={mods.Virustotal_link} target="_blank"  >Report</a></p>
                  </div>
                </div>
              </div>
              <div className="flex flex-col  gap-2 px-2 " >
                <button className="flex items-center justify-center gap-1  w-[180px] p-1 rounded-[0.5rem] bg-[#ff6600] hover:bg-[#ff6600]/90 transition-colors">
                  <Download className="w-5 h-5 stroke-3 text-white" />
                  <p className="text-[1.5rem] font-[900]">Download</p>
                </button>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
