import Image from "next/image";
import SplitText from "../components/SplitText";
import DecryptedText from '../components/DecryptedText';
import Grainient from '../components/Grainient';
import{CarFront,ArrowUpRight,Map,Truck,CalendarFold,FolderArchive} from 'lucide-react';
import { div } from "motion/react-client";
import Link from "next/link";

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Mods Haven - Mods",
  description: "Generated by create next app",
  icons: {
    icon: '/icon/logo_1.ico', 
  },
};


export default function Home() {
  return (
    <>
      <div style={{ position: 'fixed', inset: 0, zIndex: 0, width: '100%', height: '100%' }}>
        <Grainient
          color1="#202020"
          color2="#717171"
          color3="#202020"
          timeSpeed={0.4}
          colorBalance={0}
          warpStrength={0.3}
          warpFrequency={5}
          warpSpeed={2}
          warpAmplitude={50}
          blendAngle={0}
          blendSoftness={0.05}
          rotationAmount={500}
          noiseScale={2}
          grainAmount={0.1}
          grainScale={2}
          grainAnimated={false}
          contrast={1.5}
          gamma={1}
          saturation={1}
          centerX={0}
          centerY={0}
          zoom={1.5}
        />
      </div>
      <div className="relative z-10 justify-center  m-8 flex flex-row gap-8" style={{ minHeight: '100vh', padding: '48px 0' }}>
        {/* Sidebar */}
        <aside
          className="w-[320px] bg-black/40 backdrop-blur-lg border-2 border-[#ff6600] rounded-[1rem] p-8 flex flex-col gap-6"
          style={{ minHeight: '80vh', position: 'sticky', top: 32, alignSelf: 'flex-start' }}
        >
          <h3 className="font-bold text-xl mb-4 text-[#ff6600]">Filter Mods</h3>
          <form className="flex flex-col gap-4">
            {/* Search */}
            <div>
              <label className="font-semibold">Search</label>
              <input type="text" placeholder="Search mods..." className="w-full mt-2 p-2 rounded bg-[#282934] text-white" />
            </div>
            {/* Mod Type */}
            <div>
              <label className="font-semibold">Type of Mod</label>
              <select className="w-full mt-2 p-2 rounded bg-[#282934] text-white">
                <option value="all">All</option>
                <option value="car">Car</option>
                <option value="map">Map</option>
                <option value="skin">Skin</option>
                <option value="other">Other</option>
              </select>
            </div>
            {/* Car Brand */}
            <div>
              <label className="font-semibold">Car Brand</label>
                <select className="w-full mt-2 p-2 rounded bg-[#282934] text-white">
                  <option value="all">All</option>
                  <option value="aston_martin">Aston Martin</option>
                  <option value="AUDI">AUDI</option>
                  <option value="BMW">BMW</option>
                  <option value="bugatti">Bugatti</option>
                  <option value="Chevrolet">Chevrolet</option>
                  <option value="Dodge">Dodge</option>
                  <option value="Ferrari">Ferrari</option>
                  <option value="ford">Ford</option>
                  <option value="Honda">Honda</option>
                  <option value="Infiniti">Infiniti</option>
                  <option value="kia">Kia</option>
                  <option value="lamborghini">Lamborghini</option>
                  <option value="landrover">Land Rover</option>
                  <option value="Lexus">Lexus</option>
                  <option value="Lotus">Lotus</option>
                  <option value="Mazda">Mazda</option>
                  <option value="mclaren">McLaren</option>
                  <option value="mercedes">Mercedes</option>
                  <option value="Mitsubishi">Mitsubishi</option>
                  <option value="nissan">Nissan</option>
                  <option value="Pagani">Pagani</option>
                  <option value="peugeot">Peugeot</option>
                  <option value="porsche">Porsche</option>
                  <option value="renault">Renault</option>
                  <option value="Subaru">Subaru</option>
                  <option value="toyota">Toyota</option>
                  <option value="volkswagen">Volkswagen</option>
                  <option value="volvo">Volvo</option>
                </select>
              </div>
            {/* Game */}
            <div>
              <label className="font-semibold">Game</label>
              <div className="w-full mt-2 flex gap-2 items-center">
                <label className="flex items-center gap-2 cursor-pointer">
                  <input type="radio" name="game" value="all" defaultChecked className="accent-[#ff6600]" />
                  <span>All</span>
                </label>
                <label className="flex items-center gap-2 cursor-pointer">
                  <input type="radio" name="game" value="BeamNG.drive" className="accent-[#ff6600]" />
                  <Image src="/icon/icon-beamng.ico" alt="BeamNG.drive" width={24} height={24} style={{ borderRadius: 4 }} />
                </label>
                <label className="flex items-center gap-2 cursor-pointer">
                  <input type="radio" name="game" value="Assetto Corsa" className="accent-[#ff6600]" />
                  <Image src="/icon/icon-assetto.ico" alt="Assetto Corsa" width={24} height={24} style={{ borderRadius: 4 }} />
                </label>
              </div>
            </div>
            {/* Sort By */}
            <div>
              <label className="font-semibold">Sort By</label>
              <select className="w-full mt-2 p-2 rounded bg-[#282934] text-white">
                <option value="latest">Latest</option>
                <option value="oldest">Oldest</option>
                <option value="downloads">Most Downloaded</option>
                <option value="featured">Featured</option>
              </select>
            </div>
            
            <button type="submit" className="mt-4 bg-[#ff6600] text-white font-bold py-2 rounded-[0.5rem]">Apply Filters</button>
          </form>
        </aside>
        {/* Main Content Placeholder */}
        <main className="flex-1 p-8">
          <h1 className="font-bold text-3xl mb-8 text-white">Browse Mods</h1>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
            {/* Example mods data, replace with real data */}
            {[
               {
  "_id": {
    "$oid": "68c15edd0c10e9cc2ae3f85b"
  },
  "name": "Lexus LFA",
  "description": "Experience the V10 symphony with the Lexus LFA mod for BeamNG.drive! Drive this legendary supercar with stunning detail and realistic handling. #BeamNG #LexusLFA #Supercar #CarMod #V10",
  "author": "Phaien",
  "game": "BeamNG.drive",
  "downloads_size": "183 MB",
  "AD_link": "https://sawutser.top/4/9283523",
  "download_link": "https://download.modshaven.com/Lexus_LFA_revamped.zip",
  "mod_image": "https://image.modshaven.com/mods/1765456304016-1757503197833-2012_lexus_lfa_nurburgring_package_by_bhw2279_dfe5mef-fullview.webp",
  "date_added": {
    "$date": "2025-09-10T00:00:00.000Z"
  },
  "createdAt": {
    "$date": "2025-09-10T11:19:57.851Z"
  },
  "updatedAt": {
    "$date": "2026-02-24T00:51:00.283Z"
  },
  "__v": 3,
  "downloads": 3076,
  "images": [
    "https://image.modshaven.com/mods/1765456304837-1757503197833-2012_lexus_lfa_nurburgring_package_by_bhw2279_dfe5mef-fullview.webp"
  ],
  "ads_mode": 1,
  "brand": "Lexus",
  "mod_type": "car",
  "featured": false,
  "slug": "lexus-lfa",
  "tags": [],
  "Virustotal_link": "https://www.virustotal.com/gui/file/fb821ed4be0b2f46557d63c7775929c2027ee3c2e1f0bf0f2caa5da041ce3ff7"
}
            ].map((mod) => (
              <div className="bg-black/30 backdrop-blur-lg   hover:border-[#ff6600]  border-transparent  border-2   hover:scale-101 transition-all duration-300 rounded-[1rem] p-4 flex flex-col gap-4" key={mod._id.$oid}>
                <div>
                    <img src={mod.mod_image} alt={mod.name} className="w-full  object-cover rounded-[1rem]" />
                </div>
                <div className="flex flex-col gap-1 px-2">
                    <h2 className=" text-lg text-[#ff6600] font-[900]">{mod.name}</h2>
                    <p className="text-sm text-white font-[700]">By {mod.author}</p>
                </div>
                  <div className="flex gap-2 px-2">
                    <p className="text-[12px] text-[#a5a6b4] font-[900] flex gap-1"><FolderArchive className="w-4 h-4 text-white"/>{mod.downloads_size}</p>
                    <p className="text-[12px] text-[#a5a6b4] font-[900] flex gap-1"><CalendarFold className="w-4 h-4 text-white" />{mod.date_added.$date.split('T')[0]}</p>
                </div>
                <div className="flex flex-col gap-2 " >
                  <div className="border-2 border-[#563a1a] w-[150px] p-1 rounded-[0.5rem] bg-[#362a1f] flex items-center justify-center gap-2">
                    <img src={mod.game === "BeamNG.drive" ? "/icon/icon-beamng.ico" : "/icon/icon-assetto.ico"} alt={mod.game} width={24} height={24} style={{ borderRadius: 4 }} /> 
                     <p className="text-[12px] font-[700]"> {mod.game}</p>
                  </div>
                  <div className="flex  gap-2 " >
                    <div className="flex items-center justify-center gap-2 border-2 border-[#3b2352] w-25 p-1 rounded-[0.5rem] bg-[#2a2036]                                    "> 
                      <img src={`/icon/brands/${mod.brand}.svg`} alt={mod.brand} width={24} height={24} style={{ borderRadius: 4 }} /> 
                      <p className="text-[12px] font-[700]">{mod.brand}</p>
                    </div>
                  <div className="flex item-center justify-center gap-2 border-2 w-25 p-1 rounded-[0.5rem] bg-[#222938] border-[#294371]">
                    <div className="flex item-center justify-center">
                       {mod.mod_type === "car" && <CarFront className="w-4 h-4 " />}
                     {mod.mod_type === "truck" && <Truck className="w-4 h-4 " />}
                     {mod.mod_type === "map" && <Map className="w-4 h-4 " />}
                    </div>
                    <p className="text-[12px] font-[700]"> {mod.mod_type}</p>
                  </div>
                  </div>
                </div>
              
                <Link
                  href={`/mods/${encodeURIComponent(mod.name)}`}
                  className="border-2 border-[#ff6600] w-10 p-2 rounded-[50%] bg-[#282934] flex items-center justify-center hover:bg-[#362a1f] hover:text-white transition-colors"
                  title={`Go to ${mod.name}`}
                >
                  <ArrowUpRight className="w-5 h-5 text-[#ff6600] group-hover:text-white" />
                </Link>
                <div>

                </div>
                </div>
            ))}
          </div>
        </main>
      </div>
    </>
  );
}
